goplantuml -recursive -hide-connections -show-implementations -show-compositions -hide-methods  -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer,/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/testing" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/runtime.puml
goplantuml -recursive -hide-connections -show-implementations -show-compositions   -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/runtime/serializer.puml
goplantuml -recursive -hide-connections -show-implementations -show-compositions   -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1 > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/apis/meta/v1.puml
goplantuml -recursive -hide-connections -show-implementations -show-compositions -hide-methods  -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest/resttest" /home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest > /home/tao/code/github/tools/uml/k8s/staging/apiserver/pkg/registry/rest.puml
goplantuml -hide-connections -show-implementations -hide-methods -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer,/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/testing," /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1 > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/runtime_meta.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/codec > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/codec.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/schema > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/schema.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/storage > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/storage.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/reset_store > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/reset_store.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/daemonset > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/daemonset.puml
