goplantuml -hide-connections -show-implementations -show-compositions -hide-methods -recursive  -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer,/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/testing" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/runtime.puml
goplantuml -hide-connections -show-implementations -show-compositions -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/runtime/serializer.puml
goplantuml -hide-connections -show-implementations -show-compositions -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1 > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/apis/meta/v1.puml
goplantuml -hide-connections -show-implementations -show-compositions -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/labels > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/labels.puml
goplantuml -hide-connections -show-implementations -show-compositions -hide-methods -recursive  -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest/resttest" /home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/registry/rest > /home/tao/code/github/tools/uml/k8s/staging/apiserver/pkg/registry/rest.puml
goplantuml -hide-connections -show-implementations -show-compositions -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/etcd3 > /home/tao/code/github/tools/uml/k8s/staging/apiserver/pkg/storage/etcd3.puml
goplantuml -hide-connections -show-implementations -show-compositions -hide-methods -hide-fields -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/server > /home/tao/code/github/tools/uml/k8s/staging/apiserver/pkg/server.puml
goplantuml -hide-connections -show-implementations -show-compositions -hide-methods -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/apiserver/pkg/endpoints > /home/tao/code/github/tools/uml/k8s/staging/apiserver/pkg/endpoints.puml
goplantuml -hide-connections -show-implementations -show-compositions -recursive  -ignore "" /home/tao/code/github/kubernetes/staging/src/k8s.io/kube-aggregator/pkg/apiserver > /home/tao/code/github/tools/uml/k8s/staging/kube-aggregator/pkg/apiserver.puml
goplantuml -hide-connections -show-implementations -show-compositions -hide-methods -recursive  -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/testdata,/home/tao/code/github/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1/fake" /home/tao/code/github/kubernetes/staging/src/k8s.io/client-go/kubernetes/typed/apps/v1 > /home/tao/code/github/tools/uml/k8s/staging/client-go/kubernetes/typed/apps/v1.puml
goplantuml -hide-connections -show-implementations -show-compositions -hide-methods -recursive  -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/client-go/tools/cache/testing,/home/tao/code/github/kubernetes/staging/src/k8s.io/client-go/tools/cache/synctrack" /home/tao/code/github/kubernetes/staging/src/k8s.io/client-go/tools/cache > /home/tao/code/github/tools/uml/k8s/staging/client-go/tools/cache.puml
goplantuml -hide-connections -show-implementations -hide-methods -ignore "/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/serializer,/home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/testing," /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime /home/tao/code/github/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1 > /home/tao/code/github/tools/uml/k8s/staging/apimachinery/pkg/runtime_meta.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/apiserver > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/apiserver.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/codec > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/codec.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/schema > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/schema.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/storage > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/storage.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/reset_store > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/reset_store.puml
goplantuml -show-implementations   -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/daemonset > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/daemonset.puml
goplantuml -show-implementations -recursive  -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/client-go > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/client-go.puml
goplantuml -show-implementations -recursive  -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/store > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/store.puml
goplantuml -show-implementations -recursive  -ignore "" /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/queue > /home/tao/code/github/tools/uml/k8s/gen_puml/tmp/queue.puml
