staging:
    apimachinery:
        pkg:
            runtime:
                filter: ['serializer', 'testing']
                options: ['-hide-methods', '-recursive']
                serializer:
                    filter: []
                    options: ['-recursive']
            apis:
                meta:
                    v1:
                        filter: []
                        options: ['-recursive']
            labels:
                filter: []
                options: ['-recursive']
    apiserver:
        pkg:
            registry:
                rest:
                    filter: ['resttest']
                    options: ['-hide-methods', '-recursive']
            storage:
                etcd3:
                    filter: []
                    options: ['-recursive']
            server:
                filter: []
                options: ['-hide-methods', '-hide-fields', '-recursive']
            endpoints:
                filter: []
                options: ['-hide-methods', '-recursive']
    kube-aggregator:
        pkg:
            apiserver:
                options: ['-recursive']
    client-go:
        kubernetes:
            typed:
                apps:
                    v1:
                        filter: ['testdata', 'fake']
                        options: ['-hide-methods', '-recursive']
        tools:
            cache:
                filter: ['testing', 'synctrack']
                options: ['-hide-methods', '-recursive']
            record:
                filter: ['event_test', 'events_cache_test', 'main_test']
                options: ['-recursive']

combine:
    runtime_meta: ['apimachinery/pkg/runtime', 'apimachinery/pkg/apis/meta/v1']

define:
    apiserver:
        includes:
        - 'apiserver/pkg/server/genericapiserver.go'
        - 'kube-aggregator/pkg/apiserver/apiserver.go'
        - 'apiextensions-apiserver/pkg/apiserver/apiserver.go'
    codec: 
        includes:
        - 'apimachinery/pkg/runtime/serializer/versioning/versioning.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
        - 'apimachinery/pkg/runtime/serializer/codec_factory.go'
    schema:
        includes:
        - 'apimachinery/pkg/runtime/scheme.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
        - 'apimachinery/pkg/runtime/converter.go'
        - 'apimachinery/pkg/runtime/scheme_builder.go'
    storage:
        options:
        includes:
        - 'apiserver/pkg/storage/interfaces.go'
        - 'apiserver/pkg/storage/etcd3/store.go'
        - 'apiserver/pkg/registry/generic/registry/dryrun.go'
        # - 'apiserver/pkg/registry/generic/registry/dryrun.go'
    reset_store:
        options:
        # - -hide-methods
        includes:
        - 'apiserver/pkg/storage/interfaces.go'
        - 'apiserver/pkg/registry/generic/registry/store.go'
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apiserver/pkg/registry/rest/update.go'
        - 'apiserver/pkg/registry/rest/create.go'
        - 'apiserver/pkg/registry/rest/delete.go'
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
    daemonset:
        options:
        # - -hide-methods
        includes:
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apiserver/pkg/registry/rest/update.go'
        - 'apiserver/pkg/registry/rest/create.go'
        - 'apiserver/pkg/registry/rest/delete.go'
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
        - 'kubernetes/pkg/registry/apps/daemonset/strategy.go'
        - 'kubernetes/pkg/registry/apps/daemonset/storage/storage.go'
    client-go:
        options: ['-recursive']
        includes:
        - 'client-go/rest/client.go'
        - 'client-go/rest/config.go'
        - 'client-go/rest/request.go'
        - 'client-go/tools/cache/listers.go'
        - 'client-go/tools/cache/listwatch.go'
    store:
        options: ['-recursive']
        includes:
        - 'client-go/tools/cache/store.go'
        - 'client-go/tools/cache/thread_safe_store.go'
        - 'client-go/tools/cache/index.go'
    queue:
        options: ['-recursive']
        includes:
        - 'client-go/tools/cache/index.go'
        - 'client-go/tools/cache/store.go'
        - 'client-go/tools/cache/fifo.go'
        - 'client-go/tools/cache/delta_fifo.go'
    event:
        options: ['-recursive']
        includes:
        - 'client-go/tools/record/event.go'
        - 'client-go/tools/record/events_cache.go'
        - 'client-go/tools/record/fake.go'
        - 'apimachinery/pkg/watch/mux.go'
    reflector:
        options: ['-recursive']
        includes:
        # - 'client-go/tools/cache/listers.go'
        - 'client-go/tools/cache/reflector.go'
    informer:
        options: ['-recursive']
        includes:
        - 'client-go/tools/cache/controller.go'
        - 'client-go/tools/cache/shared_informer.go'
        # - 'client-go/informers/factory.go'
        # - 'client-go/informers/apps/interface.go'
        # - 'client-go/informers/apps/v1/interface.go'
        # - 'client-go/informers/apps/v1/deployment.go'
    informer-factory:
        options: ['-recursive']
        includes:
        # - 'client-go/tools/cache/controller.go'
        # - 'client-go/tools/cache/shared_informer.go'
        - 'client-go/informers/factory.go'
        - 'client-go/informers/apps/interface.go'
        - 'client-go/informers/apps/v1/interface.go'
        - 'client-go/informers/apps/v1/deployment.go'