staging:
    apimachinery:
        pkg:
            runtime:
                filter: ['serializer', 'testing']
                options: ['-hide-methods', '-recursive']
                serializer:
                    filter: []
                    options: ['-recursive']
            apis:
                meta:
                    v1:
                        filter: []
                        options: ['-recursive']
            labels:
                filter: []
                options: ['-recursive']
    apiserver:
        pkg:
            registry:
                rest:
                    filter: ['resttest']
                    options: ['-hide-methods', '-recursive']
            storage:
                etcd3:
                    filter: []
                    options: ['-recursive']
            server:
                filter: []
                options: ['-hide-methods', '-hide-fields', '-recursive']
            endpoints:
                filter: []
                options: ['-hide-methods', '-recursive']

combine:
    runtime_meta: ['apimachinery/pkg/runtime', 'apimachinery/pkg/apis/meta/v1']

define:
    codec: 
        includes:
        - 'apimachinery/pkg/runtime/serializer/versioning/versioning.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
        - 'apimachinery/pkg/runtime/serializer/codec_factory.go'
    schema:
        includes:
        - 'apimachinery/pkg/runtime/scheme.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
        - 'apimachinery/pkg/runtime/converter.go'
        - 'apimachinery/pkg/runtime/scheme_builder.go'
    storage:
        options:
        includes:
        - 'apiserver/pkg/storage/interfaces.go'
        - 'apiserver/pkg/storage/etcd3/store.go'
        - 'apiserver/pkg/registry/generic/registry/dryrun.go'
        # - 'apiserver/pkg/registry/generic/registry/dryrun.go'
    reset_store:
        options:
        # - -hide-methods
        includes:
        - 'apiserver/pkg/storage/interfaces.go'
        - 'apiserver/pkg/registry/generic/registry/store.go'
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apiserver/pkg/registry/rest/update.go'
        - 'apiserver/pkg/registry/rest/create.go'
        - 'apiserver/pkg/registry/rest/delete.go'
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
    daemonset:
        options:
        # - -hide-methods
        includes:
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apiserver/pkg/registry/rest/update.go'
        - 'apiserver/pkg/registry/rest/create.go'
        - 'apiserver/pkg/registry/rest/delete.go'
        - 'apiserver/pkg/registry/rest/rest.go'
        - 'apimachinery/pkg/runtime/interfaces.go'
        - 'kubernetes/pkg/registry/apps/daemonset/strategy.go'
        - 'kubernetes/pkg/registry/apps/daemonset/storage/storage.go'